# Generated by Django 2.2.6 on 2019-11-01 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jobs',
            new_name='job',
        ),
    ]
